### ISSUE TITLE
What does MersenneTwisterFast().nextInt() do?

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#17]
so I have this code in my OptionsDialog to generate a random seed, however, it seems to always return 0, while in the old GUI it returns some large random number

**Comment by fstonedahl** [comment]
It should return a random number in the whole range of possible integers.  (For some technical reasons, NetLogo uses a special random number generator, rather than the built-in Java methods.)

That's odd that it is always returning 0 for you.  Are you sure?  Perhaps you are missing some other initialization code that was in the old GUI?
