### ISSUE TITLE
SearchTask and SearchManager relationship

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#20]
could you explain these 2 class underline mechanism? SeachManager have method calling method in SearchTask but I don't know hour they got triggered

**Comment by fstonedahl** [comment]
When running a long-running task (like the search process), you need to do this in a separate thread from the main GUI thread, so that the GUI doesn't freeze while it's running.

Swing provides a nice mechanism for this by using a SwingWorker -- read this: https://docs.oracle.com/javase/tutorial/uiswing/concurrency/worker.html

Of course, it could also be done using the basic Java Threads... but SwingWorker seemed more convenient. 

This might be helpful:
http://stackoverflow.com/questions/27832347/javafx-swingworker-equivalent
