### ISSUE TITLE
keep track of working model

### ISSUE THREAD

**Issue by annguyendang14** [annguyendang14/behaviorsearch#7]
so I put a file chooser for the browse model button, it working fine. I wonder if the TextField for the model should also be a way to choose a model (like if user want to copy their path in the field)? If that the case, should i use a variable to keep track of the current model. if not, i could restrict the TextField so user can't change it.

Also, i found in the BehaviorSearchGUI a variable call currentFile, which file this var keep track of?

**Comment by fstonedahl** [comment]
I think it is nice (and possibly even necessary) for people to be able to type the filename of the model directly into a textbox (as well as browse for it), because they may want to set it to a RELATIVE path:  e.g. "../myModels/XYZ.nlogo", because they could be running BehaviorSearch on a remote machine where the folder structure is different.

**currentFile** keeps track of the current "search protocol file" that is loaded -- i.e. the ".bsearch" file.  This is what saves ALL the information related to the search configuration -- basically, the contents of all of the GUI components that you are creating get serialized into this file, which is in XML format.  You can take a look at a couple of those files inside the **examples** folder.
